### ISSUE TITLE
Not portable - doesn't work with Python < 3.8

### ISSUE THREAD

**Issue by arranstewart** [bristol-d/bbquiz#1]
One of the source files, `jumbled.py`, uses the Python 3.8 "Walrus operator" (`:=`), which does not work with earlier versions of Python.

https://github.com/bristol-d/bbquiz/blob/1c8088050d4850cb8dd31e75125695b69985a90b/src/jumbled.py#L54

As a result, trying to run `bbquiz` with earlier versions of Python results in an error like this:

```
Traceback (most recent call last):
  File "src/main.py", line 1, in <module>
    import BBparser as parser
  File "/home/user/bbquiz/src/BBparser.py", line 2, in <module>
    import questions
  File "/home/user/bbquiz/src/questions.py", line 6, in <module>
    import jumbled
  File "/home/user/bbquiz/src/jumbled.py", line 54
    while (m := re.search(expr, text)):
             ^
SyntaxError: invalid syntax
```

This line could be made portable to earlier versions of Python with very little effort:

```python
        while True:
            m = re.search(expr, text)
            if not m:
              break
```

**Version information**:

Python 3.6.9, running on Ubuntu 18.04, with the current HEAD (31ec074dc7dade7a1af257f342f6abb027913ffc).

**Comment by bristol-d** [comment]
Hi Arran, thanks for this - I've changed it to the backwards-compatible one and pushed to master (another merge from develop into master was overdue anyway). Let me know if there's any more problems like this, although I'm on python 3.9.1 myself it's really no effort to make a small change like this to make it more widely usable.

**Comment by arranstewart** [comment]
No worries - after I made that one change, everything else seemed to work perfectly. Such a relief to be able to use it instead of grappling with Blackboard's UI - cheers :)
