### ISSUE TITLE
Suggested feature - package for use with `pip`

### ISSUE THREAD

**Issue by arranstewart** [bristol-d/bbquiz#2]
I wondered if you'd be interested in adding a `setup.py` and `MANIFEST.in` file so that bbquiz can be installed using `pip`.

It looks like the code is currently set up with the intention that `src/main.py` be run from within the cloned Git repository. Packaging it for pip would allow users to install bbquiz with one command (e.g. "`pip install https://github.com/bristol-d/bbquiz/archive/refs/heads/master.zip`"), and they'd then be able to run "`bbquiz`" as a command from any directory (handy for users that aren't intending to do development on bbquiz).

I've made what I think would be the minimal changes for this to work in a branch [here](https://github.com/arranstewart/bbquiz/tree/feature/package-for-pip); they are

- making `bbquiz` a Python package - this involves moving the code into `src/bbquiz`, and adding an `__init__.py` file.
- adjusting some of the `import` statements so they work properly with the package structure
- adding a `setup.py` and `MANIFEST.in` file (and adding installation instructions to the README). (Normally there'd also be an "author" and "author_email" field in the setup.py, but I don't know what those should be.)
- Giving the template files in `src/templates` a common suffix – I chose "`.txt`" – so they can be easily found by the MANIFEST file and included in the package. (There are probably other ways of including them – e.g. listing them all explicitly – but this was the simplest method I found that worked.)

And here's the list of commits:

- <https://github.com/arranstewart/bbquiz/compare/cbc0578597f4a1c704d0c723277816ad2ce946f4...feature/package-for-pip>

I'd be happy to make a pull request if you're interested – let me know.

**Comment by bristol-d** [comment]
That's a great idea - happy to accept a pull request!

**Comment by bristol-d** [comment]
Actually, I've gone ahead and pulled from your fork - should be done now.

**Comment by arranstewart** [comment]
Awesome! I was just about to say: No worries, but I'm right in the middle of marking mid-semester tests, so give me a few days. But all is done, so thanks very much!
